In [12]:
import pandas as pd

meteorites = pd.read_csv('../data/Meteorite_Landings.csv')
meteorites

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"
...,...,...,...,...,...,...,...,...,...,...
45711,Zillah 002,31356,Valid,Eucrite,172.0,Found,01/01/1990 12:00:00 AM,29.03700,17.01850,"(29.037, 17.0185)"
45712,Zinder,30409,Valid,"Pallasite, ungrouped",46.0,Found,01/01/1999 12:00:00 AM,13.78333,8.96667,"(13.78333, 8.96667)"
45713,Zlin,30410,Valid,H4,3.3,Found,01/01/1939 12:00:00 AM,49.25000,17.66667,"(49.25, 17.66667)"
45714,Zubkovsky,31357,Valid,L6,2167.0,Found,01/01/2003 12:00:00 AM,49.78917,41.50460,"(49.78917, 41.5046)"
45715,Zulu Queen,30414,Valid,L3.7,200.0,Found,01/01/1976 12:00:00 AM,33.98333,-115.68333,"(33.98333, -115.68333)"

In [4]:
type(meteorites)

pandas.core.frame.DataFrame

In [13]:
meteorites.shape

(45716, 10)

In [14]:
meteorites.dtypes

name            object
id               int64
nametype        object
recclass        object
mass (g)       float64
fall            object
year            object
reclat         float64
reclong        float64
GeoLocation     object
dtype: object

In [17]:
meteorites.head(n=10)

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"
5,Adhi Kot,379,Valid,EH4,4239.0,Fell,01/01/1919 12:00:00 AM,32.10000,71.80000,"(32.1, 71.8)"
6,Adzhi-Bogdo (stone),390,Valid,LL3-6,910.0,Fell,01/01/1949 12:00:00 AM,44.83333,95.16667,"(44.83333, 95.16667)"
7,Agen,392,Valid,H5,30000.0,Fell,01/01/1814 12:00:00 AM,44.21667,0.61667,"(44.21667, 0.61667)"
8,Aguada,398,Valid,L6,1620.0,Fell,01/01/1930 12:00:00 AM,-31.60000,-65.23333,"(-31.6, -65.23333)"
9,Aguila Blanca,417,Valid,L,1440.0,Fell,01/01/1920 12:00:00 AM,-30.86667,-64.55000,"(-30.86667, -64.55)"

In [16]:
meteorites.tail()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
45711,Zillah 002,31356,Valid,Eucrite,172.0,Found,01/01/1990 12:00:00 AM,29.03700,17.01850,"(29.037, 17.0185)"
45712,Zinder,30409,Valid,"Pallasite, ungrouped",46.0,Found,01/01/1999 12:00:00 AM,13.78333,8.96667,"(13.78333, 8.96667)"
45713,Zlin,30410,Valid,H4,3.3,Found,01/01/1939 12:00:00 AM,49.25000,17.66667,"(49.25, 17.66667)"
45714,Zubkovsky,31357,Valid,L6,2167.0,Found,01/01/2003 12:00:00 AM,49.78917,41.50460,"(49.78917, 41.5046)"
45715,Zulu Queen,30414,Valid,L3.7,200.0,Found,01/01/1976 12:00:00 AM,33.98333,-115.68333,"(33.98333, -115.68333)"

In [18]:
meteorites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45716 entries, 0 to 45715
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         45716 non-null  object
 1   id           45716 non-null  int64
 2   nametype     45716 non-null  object
 3   recclass     45716 non-null  object
 4   mass (g)     45585 non-null  float64
 5   fall         45716 non-null  object
 6   year         45425 non-null  object
 7   reclat       38401 non-null  float64
 8   reclong      38401 non-null  float64
 9   GeoLocation  38401 non-null  object
dtypes: float64(3), int64(1), object(6)
memory usage: 3.5+ MB

In [21]:
meteorites[['name', 'mass (g)']]

             name  mass (g)
0          Aachen      21.0
1          Aarhus     720.0
2            Abee  107000.0
3        Acapulco    1914.0
4         Achiras     780.0
...           ...       ...
45711  Zillah 002     172.0
45712      Zinder      46.0
45713        Zlin       3.3
45714   Zubkovsky    2167.0
45715  Zulu Queen     200.0

[45716 rows x 2 columns]

In [22]:
meteorites[100:110]

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
100,Benton,5026,Valid,LL6,2840.0,Fell,01/01/1949 12:00:00 AM,45.95000,-67.55000,"(45.95, -67.55)"
101,Berduc,48975,Valid,L6,270.0,Fell,01/01/2008 12:00:00 AM,-31.91000,-58.32833,"(-31.91, -58.32833)"
102,Béréba,5028,Valid,Eucrite-mmict,18000.0,Fell,01/01/1924 12:00:00 AM,11.65000,-3.65000,"(11.65, -3.65)"
103,Berlanguillas,5029,Valid,L6,1440.0,Fell,01/01/1811 12:00:00 AM,41.68333,-3.80000,"(41.68333, -3.8)"
104,Berthoud,47355,Valid,Eucrite-mmict,960.0,Fell,01/01/2004 12:00:00 AM,40.30583,-105.02325,"(40.30583, -105.02325)"
105,Bethlehem,5032,Valid,H,13.9,Fell,01/01/1859 12:00:00 AM,42.53333,-73.83333,"(42.53333, -73.83333)"
106,Beuste,5034,Valid,L5,2000.0,Fell,01/01/1859 12:00:00 AM,43.21667,-0.23333,"(43.21667, -0.23333)"
107,Beyrout,5035,Valid,LL3.8,1100.0,Fell,01/01/1921 12:00:00 AM,33.88333,35.50000,"(33.88333, 35.5)"
108,Bhagur,5037,Valid,L6,18.0,Fell,01/01/1877 12:00:00 AM,20.88333,74.83333,"(20.88333, 74.83333)"
109,Bhawad,36591,Valid,LL6,678.0,Fell,01/01/2002 12:00:00 AM,26.50833,73.11528,"(26.50833, 73.11528)"

In [26]:
meteorites.iloc[100:105, [0, 3, 4, 6]]

              name       recclass  mass (g)                    year
100         Benton            LL6    2840.0  01/01/1949 12:00:00 AM
101         Berduc             L6     270.0  01/01/2008 12:00:00 AM
102         Béréba  Eucrite-mmict   18000.0  01/01/1924 12:00:00 AM
103  Berlanguillas             L6    1440.0  01/01/1811 12:00:00 AM
104       Berthoud  Eucrite-mmict     960.0  01/01/2004 12:00:00 AM

In [27]:
meteorites.loc[100:105, ['name', 'id']]

              name     id
100         Benton   5026
101         Berduc  48975
102         Béréba   5028
103  Berlanguillas   5029
104       Berthoud  47355
105      Bethlehem   5032

In [30]:
(meteorites['mass (g)'] > 50) & (meteorites.fall == 'Found')

0        False
1        False
2        False
3        False
4        False
         ...
45711     True
45712    False
45713    False
45714     True
45715     True
Length: 45716, dtype: bool

In [31]:
meteorites[(meteorites['mass (g)'] > 50) & (meteorites.fall == 'Found')]

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
37,Northwest Africa 5815,50693,Valid,L5,256.80,Found,NaN,0.00000,0.00000,"(0.0, 0.0)"
757,Dominion Range 03239,32591,Valid,L6,69.50,Found,01/01/2002 12:00:00 AM,NaN,NaN,NaN
804,Dominion Range 03240,32592,Valid,LL5,290.90,Found,01/01/2002 12:00:00 AM,NaN,NaN,NaN
1111,Abajo,4,Valid,H5,331.00,Found,01/01/1982 12:00:00 AM,26.80000,-105.41667,"(26.8, -105.41667)"
1112,Abar al' Uj 001,51399,Valid,H3.8,194.34,Found,01/01/2008 12:00:00 AM,22.72192,48.95937,"(22.72192, 48.95937)"
...,...,...,...,...,...,...,...,...,...,...
45709,Zhongxiang,30406,Valid,Iron,100000.00,Found,01/01/1981 12:00:00 AM,31.20000,112.50000,"(31.2, 112.5)"
45710,Zillah 001,31355,Valid,L6,1475.00,Found,01/01/1990 12:00:00 AM,29.03700,17.01850,"(29.037, 17.0185)"
45711,Zillah 002,31356,Valid,Eucrite,172.00,Found,01/01/1990 12:00:00 AM,29.03700,17.01850,"(29.037, 17.0185)"
45714,Zubkovsky,31357,Valid,L6,2167.00,Found,01/01/2003 12:00:00 AM,49.78917,41.50460,"(49.78917, 41.5046)"
45715,Zulu Queen,30414,Valid,L3.7,200.00,Found,01/01/1976 12:00:00 AM,33.98333,-115.68333,"(33.98333, -115.68333)"

In [34]:
meteorites.query("`mass (g)` > 1e6 and fall == 'Fell'")

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
29,Allende,2278,Valid,CV3,2000000.0,Fell,01/01/1969 12:00:00 AM,26.96667,-105.31667,"(26.96667, -105.31667)"
419,Jilin,12171,Valid,H5,4000000.0,Fell,01/01/1976 12:00:00 AM,44.05000,126.16667,"(44.05, 126.16667)"
506,Kunya-Urgench,12379,Valid,H5,1100000.0,Fell,01/01/1998 12:00:00 AM,42.25000,59.20000,"(42.25, 59.2)"
707,Norton County,17922,Valid,Aubrite,1100000.0,Fell,01/01/1948 12:00:00 AM,39.68333,-99.86667,"(39.68333, -99.86667)"
920,Sikhote-Alin,23593,Valid,"Iron, IIAB",23000000.0,Fell,01/01/1947 12:00:00 AM,46.16000,134.65333,"(46.16, 134.65333)"

In [36]:
meteorites.fall.value_counts()

fall
Found    44609
Fell      1107
Name: count, dtype: int64

In [38]:
meteorites.value_counts(subset=['nametype', 'fall'], normalize=True)

nametype  fall
Valid     Found    0.974145
          Fell     0.024215
Relict    Found    0.001641
Name: proportion, dtype: float64

In [46]:
meteorites[['mass (g)']].quantile([0.01, 0.05, 0.95, 0.99])

      mass (g)
0.01      0.44
0.05      1.10
0.95   4000.00
0.99  50600.00

In [49]:
meteorites['mass (g)'].idxmax()

16392

In [51]:
meteorites.loc[meteorites['mass (g)'].idxmax()]

name                             Hoba
id                              11890
nametype                        Valid
recclass                    Iron, IVB
mass (g)                   60000000.0
fall                            Found
year           01/01/1920 12:00:00 AM
reclat                      -19.58333
reclong                      17.91667
GeoLocation     (-19.58333, 17.91667)
Name: 16392, dtype: object

In [ ]:
meteorites.recclass.unique()

466

In [57]:
meteorites.describe(include='all')

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
count,45716,45716.000000,45716,45716,4.558500e+04,45716,45425,38401.000000,38401.000000,38401
unique,45716,NaN,2,466,NaN,2,266,NaN,NaN,17100
top,Aachen,NaN,Valid,L6,NaN,Found,01/01/2003 12:00:00 AM,NaN,NaN,"(0.0, 0.0)"
freq,1,NaN,45641,8285,NaN,44609,3323,NaN,NaN,6214
mean,NaN,26889.735104,NaN,NaN,1.327808e+04,NaN,NaN,-39.122580,61.074319,NaN
std,NaN,16860.683030,NaN,NaN,5.749889e+05,NaN,NaN,46.378511,80.647298,NaN
min,NaN,1.000000,NaN,NaN,0.000000e+00,NaN,NaN,-87.366670,-165.433330,NaN
25%,NaN,12688.750000,NaN,NaN,7.200000e+00,NaN,NaN,-76.714240,0.000000,NaN
50%,NaN,24261.500000,NaN,NaN,3.260000e+01,NaN,NaN,-71.500000,35.666670,NaN
75%,NaN,40656.750000,NaN,NaN,2.026000e+02,NaN,NaN,0.000000,157.166670,NaN
max,NaN,57458.000000,NaN,NaN,6.000000e+07,NaN,NaN,81.166670,354.473330,NaN

In [59]:
import requests

response = requests.get('https://openmensa.org/api/v2/canteens/')

if response.ok:
    payload = response.json()
else:
    print(f'Request was not successful and returned code: {response.status_code}.')
    payload = None

mensen = pd.DataFrame(payload)
mensen.head(3)

,id,name,city,address,coordinates
0,1,Mensa UniCampus Magdeburg,Magdeburg,"Pfälzer Str. 1, 39106 Magdeburg","[52.139618827301895, 11.647599935531616]"
1,2,Magdeburg Herrenkurg,Magdeburg,"Breitscheidstr. 2, 39114 Magdeburg","[52.14006658530411, 11.67566657066345]"
2,3,Mensa Stendal,Stendal,"Osterburger Str. 25, 39567 Stendal","[52.615015758022146, 11.849302053451538]"

In [63]:
mensen[mensen['name'] == "Mensateria Ohm"]

,id,name,city,address,coordinates
179,268,Mensateria Ohm,Nürnberg,"Wollentorstr. 4, 90489 Nürnberg, Germany","[49.45253836573686, 11.094603538513182]"

In [97]:
response = requests.get('https://openmensa.org/api/v2/canteens/268/meals/')

if response.ok:
    payload = response.json()
else:
    print(f'Request was not successful and returned code: {response.status_code}.')
    payload = None

meals = pd.DataFrame(payload)
meals.head(3)

meals = meals.explode('meals')
# meals['meals']
meals[meals['meals'].apply(lambda x: x['category'] in ['Vegan', 'Vegetarisch'])]

         date  closed                                              meals
0  2025-11-11   False  {'id': 24874997, 'name': 'Bunte vegane Gnocchi...
0  2025-11-11   False  {'id': 24874998, 'name': 'GrünWerk Currywurst ...
1  2025-11-12   False  {'id': 24875001, 'name': 'Linseneintopf ', 'ca...
1  2025-11-12   False  {'id': 24875002, 'name': 'Käsespätzle mit Röst...
2  2025-11-13   False  {'id': 24875004, 'name': 'Gemüseschnitzel  mit...
2  2025-11-13   False  {'id': 24875005, 'name': 'Frühlingsrolle gefül...
3  2025-11-14   False  {'id': 24875006, 'name': 'Apfelstrudel  mit Va...
3  2025-11-14   False  {'id': 24875008, 'name': 'Bulgurpfanne mit Tom...
4  2025-11-17   False  {'id': 24988510, 'name': 'Tortellini gefüllt m...
4  2025-11-17   False  {'id': 24988511, 'name': 'Tofuragout (BIO Qual...

In [103]:
meals.sort_values(['date'], ascending=False)

         date  closed                                              meals
4  2025-11-17   False  {'id': 24988509, 'name': 'Hähnchenschnitzel "P...
4  2025-11-17   False  {'id': 24988510, 'name': 'Tortellini gefüllt m...
4  2025-11-17   False  {'id': 24988511, 'name': 'Tofuragout (BIO Qual...
3  2025-11-14   False  {'id': 24875006, 'name': 'Apfelstrudel  mit Va...
3  2025-11-14   False  {'id': 24875007, 'name': 'MSC Alaska Seelachsf...
3  2025-11-14   False  {'id': 24875008, 'name': 'Bulgurpfanne mit Tom...
2  2025-11-13   False  {'id': 24875003, 'name': 'Schweinegeschnetzelt...
2  2025-11-13   False  {'id': 24875004, 'name': 'Gemüseschnitzel  mit...
2  2025-11-13   False  {'id': 24875005, 'name': 'Frühlingsrolle gefül...
1  2025-11-12   False  {'id': 24875000, 'name': 'MSC Seelachsfilet mi...
1  2025-11-12   False  {'id': 24875001, 'name': 'Linseneintopf ', 'ca...
1  2025-11-12   False  {'id': 24875002, 'name': 'Käsespätzle mit Röst...
0  2025-11-11   False  {'id': 24874997, 'name': 'Bunte vegane Gnocchi...
0  2025-11-11   False  {'id': 24874998, 'name': 'GrünWerk Currywurst ...
0  2025-11-11   False  {'id': 24874999, 'name': 'Hähnchenstreifen mit...

In [105]:
meals.groupby('date').describe()

           closed                    meals         \
            count unique    top freq count unique
date
2025-11-11      3      1  False    3     3      3
2025-11-12      3      1  False    3     3      3
2025-11-13      3      1  False    3     3      3
2025-11-14      3      1  False    3     3      3
2025-11-17      3      1  False    3     3      3


                                                          top freq
date
2025-11-11  {'id': 24874997, 'name': 'Bunte vegane Gnocchi...    1
2025-11-12  {'id': 24875000, 'name': 'MSC Seelachsfilet mi...    1
2025-11-13  {'id': 24875003, 'name': 'Schweinegeschnetzelt...    1
2025-11-14  {'id': 24875006, 'name': 'Apfelstrudel  mit Va...    1
2025-11-17  {'id': 24988509, 'name': 'Hähnchenschnitzel "P...    1

In [119]:
zeilen = [
    "Mary had a little lamb.",
    "Peter paid a pretty penny.",
    "Java sucks."
]

woerter = []
bisher_laengstes = 0
for z in zeilen:
    z = z.split()
    if len(z) > bisher_laengstes:
        bisher_laengstes = len(z)
    woerter.append(z)

for i in range(0, bisher_laengstes):
    hilf = ''
    for w in woerter:
        hilf = hilf + (w[i] if i < len(w) else '-') + ' '
    print(hilf)

Mary Peter Java
had paid sucks.
a a -
little pretty -
lamb. penny. -

In [121]:
# 1-2-hop
teiler = 3
anzahl = 16


for x in range(1, anzahl+1):
    print('hop' if x % teiler == 0 else x)

x = 1
while x <= anzahl:
    print('hop' if x % teiler == 0 else x)
    x = x + 1

1
2
hop
4
5
hop
7
8
hop
10
11
hop
13
14
hop
16
1
2
hop
4
5
hop
7
8
hop
10
11
hop
13
14
hop
16